### PR TITLE
Fixes express memory limit bug

### PR DESCRIPTION
**Pull request by 2xAA**
Whilst using this to build a project recently I managed to hit a memory(?) limit with express.
(```PayloadTooLargeError: request entity too large```)
This is remedied with setting parsing limits on the express `body-parser`.

### CODE REVIEW

**Comment by Tribex** [comment]
I have a number of questions about that, especially since `body-parser` isn't used by prerenderer by default. Any idea what caused it specifically?

**Comment by 2xAA** [comment]
Rendering very large HTML pages - a project required an extreme amount of SVG data and inline CSS with Base64 encoded imagery to be embedded in the HTML pages, the error (```PayloadTooLargeError```) seemed to only occur with those large pages.

The example included with ```webpack-prerender-plugin``` did not produce this error on the same machine.

My PR may have been premature, an issue raised before this would have been more appropriate - sorry about that.

**Comment by Tribex** [comment]
Ah, got it. If the addition of `body-parser` is somehow remedying the issue, it might be worth looking into why first. I have absolutely no idea.

**Comment by 2xAA** [comment]
Searching Google for the error brought up the remedy of ```body-parser``` - I've also got no idea why it fixes the issue, but it does 😕

**Comment by Tribex** [comment]
Alright, I think I'll leave it alone for now until I can figure out what's going wrong. Don't want to add an extra dependency just to fix an odd issue. I might look at adding a way to install your own middleware though if that might help.

**Comment by 2xAA** [comment]
It's not actually an extra dependency, it's shipped with express.
My thought was setting those options may have some affect in express internally.

>

**Pull request closed without merging**
